### ISSUE TITLE
Size -- but when?

### ISSUE THREAD

**Issue by Incognito** [tomdale/everyjs.com#22]
Change the array to include the date the array item was last updated. A few months from now, a lot could change, and this will be harder to keep track accuracy and what got updated last of unless we do this now.

**Comment by balupton** [comment]
+1

**Comment by bemson** [comment]
I disagree about changing the format of the size  property. This project - as I see it - is not about the size of it's entries; for that, see microjs.com.

I can see how size might appear central, since we may currently sort entries by this attribute. However, as the interface changes (and it will),  other attributes will be exposed, and these can also grow stale.

That said, entries should have a general last-modified time-stamp. As a js database (of sorts), it seems appropriate to capture this per "row". Then users can assess the age of an entire entry, instead of individual attributes.

**Comment by Incognito** [comment]
@bernson Oh I didn't mean every single element of the array needs a timestamp pair, that's borderline nuts at this stage.

Normalizing the data to a standard epoch format -- or any standard, as long as it's standard, will be useful.

We don't want to have people putting "Mid august '06" and "20/10/2011" and "11/21/11" all over the place.

Epoch is fine, epoch is highly accessible, it's universal, precise, compact, and works fine. 

Again, my concern isn't about sorting things by age and feature creeping the search, but keeping track of when that record was updated. So, you're looking at library ABC, and the website tells you it's 3kb and has features A, B and C. Turns out it's wrong because it hasn't been updated since 2011, and we're in 2013. Oops.

Yes, you could scour git logs to find the last change, but that's a lot of work when you look at the simple alternative of "lastUpdated" : "1307116122"

**Comment by bemson** [comment]
@0xdeadcafe My apologies. Reading your post (carefully, this time), I see that the title impacted my interpretation... I thought you wanted to only update the "size" property. :-\

We're saying the same thing! As you were. Nothing to see here. +1, etc, etc.
